# Generated by Django 2.2.8 on 2019-12-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='CLASS', max_length=255, null=True)),
                ('latitude', models.IntegerField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.IntegerField(blank=True, db_column='LONGITUDE', null=True)),
                ('map', models.CharField(blank=True, db_column='MAP', max_length=255, null=True)),
                ('elev', models.IntegerField(blank=True, db_column='ELEV', null=True)),
            ],
            options={
                'db_table': 'FEATURES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(blank=True, db_column='GENUS', max_length=255, null=True)),
                ('species', models.CharField(blank=True, db_column='SPECIES', max_length=255, null=True)),
                ('comname', models.CharField(blank=True, db_column='COMNAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'FLOWERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, primary_key=True, serialize=False)),
                ('membersince', models.DateField(blank=True, db_column='MEMBERSINCE', max_length=255, null=True)),
                ('numsightings', models.IntegerField(blank=True, db_column='NUMSIGHTINGS', null=True)),
            ],
            options={
                'db_table': 'MEMBERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, null=True)),
                ('person', models.CharField(blank=True, db_column='PERSON', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=255, null=True)),
                ('sighted', models.DateField(blank=True, db_column='SIGHTED', null=True)),
            ],
            options={
                'db_table': 'SIGHTINGS',
                'managed': False,
            },
        ),
    ]
